language: java

jdk:
  - openjdk16

matrix:
  - jdk: openjdk16
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

script:
  - mvn -Pstatic-analysis clean compile
  - mvn -Parchitecture-tests test
  - mvn -Pdomain-tests verify
  - mvn -Pintegration-tests verify
  - mvn -Psystem-tests verify